apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-backend-sa
  namespace: webapp
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-read
  namespace: webapp
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-read
  namespace: webapp
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-read
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-read
  namespace: data
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-read
  namespace: data
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-read
