apiVersion: v1
kind: ServiceAccount
metadata:
  name: minishop-backend
  namespace: webapp
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minishop-developer-pod-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minishop-developer-pod-reader
  namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minishop-developer-pod-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: minishop:developers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minishop-developer-pod-reader
  namespace: data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minishop-developer-pod-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: minishop:developers
