---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../manifests/10-data/postgresql.yaml
  - ../../../manifests/10-data/redis.yaml
  - ../../../manifests/20-webapp/backend.yaml
  - ../../../manifests/20-webapp/frontend.yaml
  - ../../../manifests/20-webapp/networkpolicy.yaml
